import { Choice } from './twee';

export interface YotoJSON {
    cardId?: string;
    userId?: string;
    slug: string;
    sortkey: string;
    metadata: Metadata;
    updatedAt: string;
    content: Content;
    skipMediaFileCheck?: boolean;
}

interface Metadata {
    author: string;
    category: string;
    cover: Cover;
    description: string;
    media?: Media;
}

interface Cover {
    imageL: string;
}

interface Media {
    duration: number;
    fileSize: number;
    hasStreams: boolean;
}

interface Content {
    cover: Cover;
    editSettings: Record<string, unknown>;
    config: Record<string, unknown>;
    chapters: Chapter[];
    playbackType: string | 'interactive';
}

export interface Chapter {
    title: string;
    key: string;
    display: Display;
    tracks: Track[];
}

interface Track {
    key: string;
    title: string;
    type: string;
    format: string;
    trackUrl: string;
    events: Record<string, TrackEvent | undefined>;
}

export interface TrackEvent {
    cmd: string;
    params?: Record<string, string>;
}

interface Display {
    icon16x16: string;
}

export interface AutoGeneratedAudio extends GeneratedAudio {
    content: string;
}

export interface GeneratedAudio {
    key: string;
    contentAudioUrl: string;
    choices: Choice[];
}
