name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to process (e.g., v1.10.1)'
        required: true
        default: 'v1.10.1'

permissions:
  contents: write
  actions: read

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: yotoplay/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug release info
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release draft: ${{ github.event.release.draft }}"
          echo "Release prerelease: ${{ github.event.release.prerelease }}"

      - name: Download release assets
        run: |
          cd homebrew-tap
          # Get the latest release info
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_TAG="${{ github.event.inputs.release_tag }}"
          else
            RELEASE_TAG="${{ github.event.release.tag_name }}"
          fi
          VERSION="${RELEASE_TAG#v}"
          
          echo "Processing release: $RELEASE_TAG"
          echo "Version: $VERSION"
          
          # Download both zip files
          curl -L -o "twine2yoto-macos-arm64.zip" \
            "https://github.com/yotoplay/twine-to-yoto/releases/download/${RELEASE_TAG}/twine2yoto-macos-arm64.zip"
          
          curl -L -o "twine2yoto-macos-x64.zip" \
            "https://github.com/yotoplay/twine-to-yoto/releases/download/${RELEASE_TAG}/twine2yoto-macos-x64.zip"
          
          # Calculate SHA256 for both
          ARM64_SHA256=$(shasum -a 256 twine2yoto-macos-arm64.zip | cut -d' ' -f1)
          X64_SHA256=$(shasum -a 256 twine2yoto-macos-x64.zip | cut -d' ' -f1)
          
          echo "ARM64 SHA256: $ARM64_SHA256"
          echo "X64 SHA256: $X64_SHA256"
          
          # Update the formula with both SHA256 values
          sed -i.bak \
            -e "s/version \"[^\"]*\"/version \"$VERSION\"/" \
            -e "s|url \"https://github.com/yotoplay/twine-to-yoto/releases/download/v[^\"]*|url \"https://github.com/yotoplay/twine-to-yoto/releases/download/v$VERSION|g" \
            -e "/arm64/,/sha256/s/sha256 \"[^\"]*\"/sha256 \"$ARM64_SHA256\"/" \
            -e "/x64/,/sha256/s/sha256 \"[^\"]*\"/sha256 \"$X64_SHA256\"/" \
            Formula/twine-to-yoto.rb
          
          # Remove backup file
          rm Formula/twine-to-yoto.rb.bak

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add Formula/twine-to-yoto.rb
            git commit -m "feat: update twine-to-yoto to ${{ github.event.release.tag_name }}"
            git remote set-url origin https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/yotoplay/homebrew-tap.git
            git push origin main
          fi 