name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to process (e.g., v1.10.1)'
        required: true
        default: 'v1.10.1'

permissions:
  contents: write
  actions: read

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v4
        with:
          repository: yotoplay/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug release info
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release draft: ${{ github.event.release.draft }}"
          echo "Release prerelease: ${{ github.event.release.prerelease }}"

      - name: Checkout twine-to-yoto (for scripts)
        uses: actions/checkout@v4
        with:
          repository: yotoplay/twine-to-yoto
          path: twine-to-yoto

      - name: Download release assets and update homebrew formula
        run: |
          cd homebrew-tap
          # Get the latest release info
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_TAG="${{ github.event.inputs.release_tag }}"
          else
            RELEASE_TAG="${{ github.event.release.tag_name }}"
          fi
          
          # Run the external script
          ../twine-to-yoto/scripts/download-release-assets.sh "$RELEASE_TAG"
          ls -al
          pwd
          git status
          git remote -v
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff
          
          git add Formula/**
          git commit -m "feat: update twine-to-yoto to ${{ github.event.release.tag_name }}"
          git remote set-url origin https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/yotoplay/homebrew-tap.git
          git push origin main
          
